# Multi-Objective Reinforcement Learning based on Decomposition with Policy Iteration

This notebook implements and evaluates our MORL personalization algorithm as described in Chapter 3 of our thesis. It trains the algorithm, discovers a Pareto-optimal set of policies, evaluates baseline methods, and conducts simulations with synthetic users. Thes results of the simulations are analyzed (in `simulation_analysis.py`) to assess the performance of our proposed method in comparison to other approaches.

**Author:** Shirley Li  
**Date:** July 2026

### Notebook Structure

The analysis follows these main phases:

1. **Data Preparation**: Load user interaction data and process it into MOMDP representation
2. **Environment Setup**: Initialize multi-objective gymnasium environment with estimated reward and transition dynamics
3. **Algorithm Training**: Train PIMORLD to discover Pareto-optimal policies
4. **Policy Analysis**: Extract and analyze discovered policies from Pareto archive
5. **Comparison Policies**: Implement multiple baseline policy methods for comparison
6. **Simulation**: Run simulations comparing all policy approaches
7. **Results Analysis**: Evaluation of metrics including adherence, retention, diversity, and dropout

### Parameters

Configuration variables (defined in `config.py`):
- **NUM_STATES**: Number of states
- **NUM_ACTIONS**: Total number of actions (challenge clusters × within-cluster selection strategies)
- **NUM_OBJECTIVES**: Number of reward objectives
- **gamma**: Discount factor
- **NUM_USERS**: Number of users (simulations) to run
- **NUM_TIMESTEPS**: Timesteps per user simulation

In [1]:
import pandas as pd
import numpy as np
import os
import mo_gymnasium as mo_gym
from env.user_sim import UserSimEnv
import env.simulate as sim_utils
import seaborn as sns
import pandas as pd
import utils.utils as utils
import utils.process_data as dp
import morld.mp_selection as mp_selection 
from morld.pi_morld import PIMORLD
import pyperclip

import utils.mdp_utils as mdp_utils
import utils.plot_figures as pf
import pickle
from morld.mo_pi import MOPolicyIteration
import config

In [2]:
state_to_idx, idx_to_state = utils.build_state_space(config.NUM_VALS_PER_FEATURE)

## Data preparation

First we load the data and process the samples

In [ ]:
results_folder = '..\\results\\'
data_folder = '..\\data\\'

action_data = pd.read_csv(os.path.join(data_folder, 'challenge_info.csv'))

samples = pd.read_csv(os.path.join(data_folder, 'processed_samples_corrected_full.csv'))
model_name_suffix = ""

actions_clustered, _, _ = dp.cluster_actions(action_data, config.cluster_vars, num_clusters=config.NUM_CLUSTERS)

df, agency_df, initial_distribution, mapping = dp.process_samples(samples, actions_clustered, config.state_features, config.NUM_VALS_PER_FEATURE, config.action_col, config.cluster_col)

For the reward estimation of some objectives, we only use data from completed challenges, as only then the reward can be observed. Otherwise the reward is 0.

In [4]:
# In some cases, the challenge was completed, but the ratings were not given (i.e. they are 0 after preprocessing).
# These are filtered out for the reward estimation
filtered_df = df[~(df['completed'] == 1 & (df['difficulty'] == 0))]

# For the stochastic rewards for simulation, we only want to use the completed samples where the ratings are given (i.e. not 0 after preprocessing)
completed_df = df[df['completed'] == 1]
completed_df = completed_df[completed_df['likedness'] != 0]

print("Total number of samples:", len(df))
print("Number of filtered samples (no nans for completed):", len(filtered_df))
print("Number of completed samples:", len(df[df['completed'] == 1]))
print("Number of filtered completed samples (no nans for completed):", len(completed_df))

Total number of samples: 3471
Number of filtered samples (no nans for completed): 3451
Number of completed samples: 2349
Number of filtered completed samples (no nans for completed): 2329

### Estimate transition and reward functions

In [5]:
# Completion probabilities, rewards, and transition probabilities for the MOMDP
P_comp = mdp_utils.compute_completion_probabilities(df, config.NUM_STATES, config.NUM_ACTIONS, config.action_col, prior='action_only')
R = mdp_utils.compute_rewards(filtered_df, config.NUM_STATES, config.NUM_ACTIONS, config.NUM_OBJECTIVES, config.reward_cols, config.action_col, mapping)
P = mdp_utils.compute_transition_probabilities(df, config.NUM_STATES, config.NUM_ACTIONS, config.action_col)

print("P shape:", P.shape)  # Should be (nU, nA, nU)
print("R shape:", R.shape)  # Should be (nU, nA, nO)

# Estimate completion probabilities for agency condition for user choice simulation
P_comp_agency = mdp_utils.compute_completion_probabilities(agency_df, config.NUM_STATES, config.NUM_ACTIONS, config.action_col, prior='action_only')

P shape: (12, 6, 12)
R shape: (12, 6, 5)

For our simulations, we use reward distributions.

In [6]:
lam = 1  # Laplace smoothing

R_probs_fun = mdp_utils.compute_reward_probabilities(completed_df, 'likedness', config.NUM_STATES, config.NUM_ACTIONS, config.action_col, lam=lam)
R_probs_pu = mdp_utils.compute_reward_probabilities(completed_df, 'usefulness', config.NUM_STATES, config.NUM_ACTIONS, config.action_col, lam=lam)
R_probs_return = mdp_utils.compute_reward_probabilities(df, 'PAY_next', config.NUM_STATES, config.NUM_ACTIONS, config.action_col, lam=lam)

R_probs = {'likedness': R_probs_fun, 'usefulness': R_probs_pu, 'PAY_next': R_probs_return}

### Challenge information
We need some information on the challenges for our simulation environment

In [7]:
challenges_per_cluster = [[i for i in range(len(actions_clustered)) if actions_clustered[config.cluster_col].iloc[i] == cluster_id] for cluster_id in range(config.NUM_CLUSTERS)]
challenge_info = actions_clustered.set_index('challenge_id').to_dict('records')

## Setup environment

In [8]:
env = mo_gym.make('user_env', num_actions=config.NUM_ACTIONS, 
                 num_objectives = config.NUM_OBJECTIVES, 
                 num_vals_per_feature=config.NUM_VALS_PER_FEATURE,
                 challenge_info=challenge_info, 
                 challenges_per_cluster=challenges_per_cluster,
                 num_categories=config.NUM_CATEGORIES,
                 transition_probs=P, 
                 completion_probs=P_comp,
                 reward_matrix=R, 
                 reward_probs=R_probs,
                 initial_distribution=initial_distribution,
                 mapping=mapping,
                 P_comp_agency=P_comp_agency,
                 agency_bias_params=config.agency_bias,
                 )

## Policy Iteration MORL/D algorithm
Setup the algorithm and train it to discover Pareto-optimal policies. The discovered policies are stored in a Pareto archive.

In [9]:
pop_size = 128
weights_init = "combined"
scalarization = "linear"
max_eval_iters = 1000
gamma = 0.7

model_name = f'pimorld_P={pop_size}_gamma={gamma}_MOT{model_name_suffix}'
filename = model_name
model_file = os.path.join(results_folder, model_name, filename)

# Initialize the PIMORLD algorithm
pi_morld = PIMORLD(env.unwrapped,
                   pop_size=pop_size, 
                   gamma=gamma,
                   max_eval_iters=max_eval_iters,
                   weights_init=weights_init,
                   scalarization=scalarization)

# Train the model
pi_morld.train(num_iterations=1000, max_resets=50)

Initial weights for agents:
[[0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.20348524 0.79651476]
 [0.         0.         0.         0.40281049 0.59718951]
 [0.         0.         0.         0.60108623 0.39891377]
 [0.         0.         0.         0.79960042 0.20039958]
 [0.         0.         0.         1.         0.        ]
 [0.         0.         0.25916169 0.50793705 0.23290126]
 [0.         0.         0.25991581 0.         0.74008419]
 [0.         0.         0.26397129 0.25308243 0.48294628]
 [0.         0.         0.49094124 0.50905876 0.        ]
 [0.         0.         0.49559295 0.25665379 0.24775326]
 [0.         0.         0.50599475 0.         0.49400525]
 [0.         0.         0.74025807 0.25974193 0.        ]
 [0.         0.         0.74849568 0.         0.25150432]
 [0.         0.         1.         0.         0.        ]
 [0.         0.2487372  0.49492772 0.         0.25633508]
 [0.         0.25373475 0.24844609 0.         0.49781916]
 [0.         0.25687029 0.48588819 0.25724152 0.        ]
 [0.         0.26055242 0.24458558 0.25273754 0.24212445]
 [0.         0.26494111 0.73505889 0.         0.        ]
 [0.         0.27331291 0.         0.         0.72668709]
 [0.         0.27361578 0.         0.72638422 0.        ]
 [0.         0.27744663 0.         0.47837956 0.24417381]
 [0.         0.2812196  0.         0.23932125 0.47945915]
 [0.         0.50090564 0.24594152 0.         0.25315284]
 [0.         0.50178712 0.49821288 0.         0.        ]
 [0.         0.50961668 0.24713197 0.24325136 0.        ]
 [0.         0.51409306 0.         0.48590694 0.        ]
 [0.         0.51800637 0.         0.         0.48199363]
 [0.         0.73904696 0.26095304 0.         0.        ]
 [0.         0.74841476 0.         0.25158524 0.        ]
 [0.         0.7492529  0.         0.         0.2507471 ]
 [0.         1.         0.         0.         0.        ]
 [0.2023068  0.46200818 0.         0.15546124 0.18022378]
 [0.2368792  0.         0.24871812 0.51440268 0.        ]
 [0.24129032 0.27106182 0.23808772 0.24956013 0.        ]
 [0.24312191 0.26720682 0.         0.48967127 0.        ]
 [0.24822666 0.25010582 0.50166752 0.         0.        ]
 [0.24960315 0.26632505 0.         0.         0.4840718 ]
 [0.24966932 0.75033068 0.         0.         0.        ]
 [0.24989909 0.         0.50288722 0.         0.24721369]
 [0.25066551 0.26592217 0.24407668 0.         0.23933564]
 [0.25377885 0.         0.74622115 0.         0.        ]
 [0.25472725 0.         0.24698106 0.25274218 0.24554952]
 [0.25560572 0.         0.48993116 0.25446313 0.        ]
 [0.25968327 0.         0.         0.74031673 0.        ]
 [0.2609315  0.         0.25688284 0.         0.48218566]
 [0.26672641 0.         0.         0.24542595 0.48784763]
 [0.2681634  0.         0.         0.48367503 0.24816157]
 [0.27375203 0.         0.         0.         0.72624797]
 [0.47479094 0.27319847 0.         0.25201059 0.        ]
 [0.47764015 0.2655844  0.25677545 0.         0.        ]
 [0.48567492 0.51432508 0.         0.         0.        ]
 [0.48977372 0.25447349 0.         0.         0.25575279]
 [0.49608314 0.         0.24822423 0.25569263 0.        ]
 [0.50388179 0.         0.49611821 0.         0.        ]
 [0.50607106 0.         0.         0.49392894 0.        ]
 [0.51020541 0.         0.24646683 0.         0.24332776]
 [0.51255807 0.         0.         0.24331956 0.24412237]
 [0.51818936 0.         0.         0.         0.48181064]
 [0.73225042 0.26774958 0.         0.         0.        ]
 [0.74690532 0.         0.25309468 0.         0.        ]
 [0.75060859 0.         0.         0.24939141 0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.32092953 0.31184992 0.31833354 0.03734878 0.01153823]
 [0.20423268 0.19822942 0.43925151 0.01114814 0.14713825]
 [0.01562034 0.24150786 0.38394867 0.08579992 0.2731232 ]
 [0.0820249  0.04884865 0.16812119 0.48071285 0.22029241]
 [0.24026011 0.04306324 0.35401308 0.23635009 0.12631348]
 [0.2301249  0.25011621 0.04252682 0.09911094 0.37812114]
 [0.12700325 0.41308604 0.23150292 0.07774483 0.15066296]
 [0.25836269 0.13846587 0.12963756 0.35394962 0.11958425]
 [0.26590315 0.27729957 0.21613597 0.01455982 0.2261015 ]
 [0.41760614 0.34597763 0.08635232 0.09895973 0.05110418]
 [0.06053695 0.00361137 0.02858998 0.224655   0.6826067 ]
 [0.32456078 0.16358814 0.22908138 0.20810929 0.07466041]
 [0.09516604 0.12086315 0.13245537 0.46645325 0.18506219]
 [0.38414052 0.24369608 0.13837758 0.01038164 0.22340417]
 [0.13689368 0.33221114 0.4467785  0.07315636 0.01096032]
 [0.12874667 0.35546751 0.1143033  0.29665356 0.10482895]
 [0.65786625 0.14458253 0.06729754 0.07133467 0.05891901]
 [0.01544014 0.48478023 0.12669262 0.10904669 0.26404031]
 [0.04768291 0.48844449 0.32896382 0.08383317 0.05107562]
 [0.14480928 0.08312751 0.02065398 0.13732098 0.61408826]
 [0.11078732 0.33849641 0.22472991 0.12276183 0.20322453]
 [0.16015321 0.23526244 0.08376765 0.04826075 0.47255594]
 [0.0694644  0.09302934 0.15360158 0.47901175 0.20489293]
 [0.11949399 0.37704459 0.26914666 0.20447109 0.02984368]
 [0.53155009 0.20310555 0.05530973 0.17850264 0.03153199]
 [0.1846339  0.19605225 0.05938002 0.00924928 0.55068454]
 [0.13539277 0.24941137 0.05913088 0.28097646 0.27508852]
 [0.01187944 0.69282465 0.08592034 0.17829062 0.03108494]
 [0.23843382 0.06937236 0.3911473  0.11222858 0.18881794]
 [0.22043381 0.31453957 0.19715375 0.25588358 0.01198929]
 [0.1924185  0.30418901 0.07041684 0.41260225 0.0203734 ]
 [0.43635711 0.05709471 0.10477943 0.38187948 0.01988927]
 [0.05881492 0.41343943 0.30252925 0.08868166 0.13653474]
 [0.18168619 0.46030384 0.08681973 0.18537244 0.08581779]
 [0.06563438 0.46015513 0.12004194 0.28888269 0.06528586]
 [0.03808968 0.2339018  0.2902159  0.19468884 0.24310379]
 [0.12976834 0.13907933 0.28717252 0.35961724 0.08436257]
 [0.01557689 0.24095908 0.145254   0.41892015 0.17928987]
 [0.06521415 0.48779743 0.26614096 0.05352909 0.12731838]
 [0.52282923 0.06060407 0.03881931 0.06679774 0.31094965]
 [0.57814684 0.10497683 0.00431654 0.23258036 0.07997943]
 [0.30648021 0.01580062 0.101432   0.15083809 0.42544909]
 [0.05954767 0.35583278 0.1565513  0.35465202 0.07341623]
 [0.10580403 0.08036928 0.3319074  0.20654903 0.27537025]
 [0.26098209 0.23478865 0.21265832 0.28456502 0.00700592]
 [0.35880117 0.31003836 0.10458415 0.05715475 0.16942158]
 [0.28320336 0.04556653 0.20038169 0.41509055 0.05575787]
 [0.62331465 0.00874917 0.00538675 0.26905625 0.09349319]
 [0.07603083 0.24578639 0.31049831 0.10340892 0.26427554]
 [0.19163549 0.09510239 0.0461404  0.26110337 0.40601834]
 [0.42904023 0.04853191 0.16484194 0.08248582 0.2751001 ]
 [0.18667611 0.04985582 0.3052543  0.0597632  0.39845058]
 [0.09405011 0.02185838 0.59513474 0.05825222 0.23070456]
 [0.216125   0.5478126  0.09716953 0.12688583 0.01200704]
 [0.43517269 0.09570404 0.18659212 0.23409032 0.04844083]
 [0.70516074 0.13141931 0.01812103 0.02597495 0.11932398]
 [0.07951635 0.20433155 0.46544405 0.02598369 0.22472436]
 [0.29380243 0.01394664 0.18160117 0.00944536 0.5012044 ]
 [0.03612539 0.03483017 0.15492201 0.32109294 0.45302949]
 [0.24831659 0.31047731 0.19711946 0.03460167 0.20948498]
 [0.05579397 0.33071199 0.25652138 0.11954638 0.23742628]
 [0.43227833 0.11101768 0.20030733 0.20253296 0.05386369]
 [0.07860825 0.27846763 0.32434246 0.15576128 0.16282039]
 [0.11147635 0.32687556 0.11382531 0.26846964 0.17935315]]
Running policy iteration with weights: [0. 0. 0. 0. 1.]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.         0.         0.20348524 0.79651476]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.         0.         0.40281049 0.59718951]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.         0.         0.60108623 0.39891377]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.         0.         0.79960042 0.20039958]
Policy converged after 2 iterations.
Running policy iteration with weights: [0. 0. 0. 1. 0.]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.         0.25916169 0.50793705 0.23290126]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.         0.25991581 0.         0.74008419]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.         0.26397129 0.25308243 0.48294628]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.         0.49094124 0.50905876 0.        ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.         0.49559295 0.25665379 0.24775326]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.         0.50599475 0.         0.49400525]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.         0.74025807 0.25974193 0.        ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.         0.74849568 0.         0.25150432]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0. 0. 1. 0. 0.]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.2487372  0.49492772 0.         0.25633508]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.25373475 0.24844609 0.         0.49781916]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.25687029 0.48588819 0.25724152 0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.26055242 0.24458558 0.25273754 0.24212445]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.26494111 0.73505889 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.27331291 0.         0.         0.72668709]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.27361578 0.         0.72638422 0.        ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.27744663 0.         0.47837956 0.24417381]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.2812196  0.         0.23932125 0.47945915]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.50090564 0.24594152 0.         0.25315284]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.50178712 0.49821288 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.50961668 0.24713197 0.24325136 0.        ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.51409306 0.         0.48590694 0.        ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.         0.51800637 0.         0.         0.48199363]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.         0.73904696 0.26095304 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.         0.74841476 0.         0.25158524 0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.        0.7492529 0.        0.        0.2507471]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0. 1. 0. 0. 0.]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.2023068  0.46200818 0.         0.15546124 0.18022378]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.2368792  0.         0.24871812 0.51440268 0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.24129032 0.27106182 0.23808772 0.24956013 0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.24312191 0.26720682 0.         0.48967127 0.        ]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.24822666 0.25010582 0.50166752 0.         0.        ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.24960315 0.26632505 0.         0.         0.4840718 ]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.24966932 0.75033068 0.         0.         0.        ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.24989909 0.         0.50288722 0.         0.24721369]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.25066551 0.26592217 0.24407668 0.         0.23933564]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.25377885 0.         0.74622115 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.25472725 0.         0.24698106 0.25274218 0.24554952]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.25560572 0.         0.48993116 0.25446313 0.        ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.25968327 0.         0.         0.74031673 0.        ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.2609315  0.         0.25688284 0.         0.48218566]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.26672641 0.         0.         0.24542595 0.48784763]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.2681634  0.         0.         0.48367503 0.24816157]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.27375203 0.         0.         0.         0.72624797]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.47479094 0.27319847 0.         0.25201059 0.        ]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.47764015 0.2655844  0.25677545 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.48567492 0.51432508 0.         0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.48977372 0.25447349 0.         0.         0.25575279]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.49608314 0.         0.24822423 0.25569263 0.        ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.50388179 0.         0.49611821 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.50607106 0.         0.         0.49392894 0.        ]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.51020541 0.         0.24646683 0.         0.24332776]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.51255807 0.         0.         0.24331956 0.24412237]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.51818936 0.         0.         0.         0.48181064]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.73225042 0.26774958 0.         0.         0.        ]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.74690532 0.         0.25309468 0.         0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.75060859 0.         0.         0.24939141 0.        ]
Policy converged after 2 iterations.
Running policy iteration with weights: [1. 0. 0. 0. 0.]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.32092953 0.31184992 0.31833354 0.03734878 0.01153823]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.20423268 0.19822942 0.43925151 0.01114814 0.14713825]
Policy converged after 3 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.01562034 0.24150786 0.38394867 0.08579992 0.2731232 ]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.0820249  0.04884865 0.16812119 0.48071285 0.22029241]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.24026011 0.04306324 0.35401308 0.23635009 0.12631348]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.2301249  0.25011621 0.04252682 0.09911094 0.37812114]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.12700325 0.41308604 0.23150292 0.07774483 0.15066296]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.25836269 0.13846587 0.12963756 0.35394962 0.11958425]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.26590315 0.27729957 0.21613597 0.01455982 0.2261015 ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.41760614 0.34597763 0.08635232 0.09895973 0.05110418]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.06053695 0.00361137 0.02858998 0.224655   0.6826067 ]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.32456078 0.16358814 0.22908138 0.20810929 0.07466041]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.09516604 0.12086315 0.13245537 0.46645325 0.18506219]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.38414052 0.24369608 0.13837758 0.01038164 0.22340417]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.13689368 0.33221114 0.4467785  0.07315636 0.01096032]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.12874667 0.35546751 0.1143033  0.29665356 0.10482895]
Policy converged after 2 iterations.
Running policy iteration with weights: [0.65786625 0.14458253 0.06729754 0.07133467 0.05891901]
Policy converged after 3 iterations.
Running policy iteration with weights: [0.01544014 0.48478023 0.12669262 0.10904669 0.26404031]
Policy converged after 2 iterations.
Policy already in archive, skipping addition.
Running policy iteration with weights: [0.04768291 0.48844449 0.32896382 0.08383317 0.05107562]

Save to file

In [10]:
save_path = os.path.join(results_folder, model_name, 'model')
save_file = "pimorld_trained.pkl"
save_to = os.path.join(save_path, save_file)
if not os.path.exists(save_path):
    os.makedirs(save_path)

with open(save_to, 'wb') as f:
    pickle.dump(pi_morld, f)

Inspect the discovered approximation set

In [11]:
print("Hypervolume of Pareto Archive: ", pi_morld.get_hv())
print("Number of solutions in Pareto Archive: ", len(pi_morld.pareto_archive.evaluations))
mp_selection.get_max_unique_actions(pi_morld.pareto_archive.individuals, config.NUM_STATES)

Hypervolume of Pareto Archive:  50.778459212276125
Number of solutions in Pareto Archive:  174

{'max_unique_actions': 6,
 'avg_unique_actions': 3.9166666666666665,
 'most_disputed_state': 10}

### Subset selection from Pareto archive
For our metapolicies explained in Chapter 3 of the thesis, we need to select a subset of policies from the discovered Pareto archive. For this we select a subset based on the Expected Utility Metric, and the one that performs the best on the expert-driven objectives.

#### User choice: subset selection based on EUM

In [12]:
rng = np.random.default_rng(66)
weight_samples = rng.dirichlet(np.ones(config.NUM_OBJECTIVES), size=10000)

policy_evals = np.array(pi_morld.pareto_archive.evaluations)
eum = mp_selection.calculate_eum(policy_evals, weight_samples)
print("Expected Utility of Pareto Archive: ", eum)

selected_indices = mp_selection.select_policies(pi_morld.pareto_archive.individuals, policy_evals, mp_selection.score_eum, max_actions=3, weight_samples=weight_samples)
print(f"Best subset of policies has EUM: {mp_selection.calculate_eum(policy_evals[selected_indices], weight_samples)}")
top_n_individuals = np.array(pi_morld.pareto_archive.individuals)[selected_indices]
top_n_evaluations = np.array(pi_morld.pareto_archive.evaluations)[selected_indices]
selected_policies = np.array([ind['policy'] for ind in top_n_individuals])

policy_morl_raw = mp_selection.get_actions_per_state(top_n_individuals, config.NUM_STATES)

display(policy_morl_raw)

Expected Utility of Pareto Archive:  2.2042139309537347

Best subset of policies has EUM: 2.2030822946588646

{0: {np.int8(1), np.int8(4)},
 1: {np.int8(1), np.int8(4), np.int8(5)},
 2: {np.int8(1), np.int8(2), np.int8(5)},
 3: {np.int8(1), np.int8(4), np.int8(5)},
 4: {np.int8(1), np.int8(4), np.int8(5)},
 5: {np.int8(2), np.int8(4), np.int8(5)},
 6: {np.int8(1), np.int8(4), np.int8(5)},
 7: {np.int8(1), np.int8(4)},
 8: {np.int8(1), np.int8(4), np.int8(5)},
 9: {np.int8(1), np.int8(4), np.int8(5)},
 10: {np.int8(1), np.int8(4), np.int8(5)},
 11: {np.int8(1), np.int8(3), np.int8(4)}}

#### Expert-priority

In [13]:
best_expert_idx = np.argmax(np.sum(policy_evals[:, 2:], axis=1))  # expert-driven objectives are the last three objectives in the evaluation
best_expert_policy = pi_morld.pareto_archive.individuals[best_expert_idx]['policy']
print("Best expert-driven policy index: ", best_expert_idx)
print("Best expert-driven policy evaluation: ", policy_evals[best_expert_idx])
print(best_expert_policy)

Best expert-driven policy index:  4
Best expert-driven policy evaluation:  [1.62372996 1.38366041 1.96744118 2.54155351 3.33333121]
[4 4 5 5 4 4 4 4 4 4 3 3]

## Obtain comparison policies

In [14]:
# Equal weights for all objectives
equal_weights = np.ones(config.NUM_OBJECTIVES) / config.NUM_OBJECTIVES
solver_equal = MOPolicyIteration(P, R, equal_weights, gamma=gamma, scalarization=scalarization)
solver_equal.train()
if pi_morld.is_in_pareto_archive(solver_equal):
    print("Equal weights policy is in the Pareto archive.")
policy_equal = solver_equal.policy_table

# Weights based on correlations with completion
correlations = df[config.reward_cols + ['completed']].corr()['completed'][:-1]
weights_correlations = np.array(correlations) / np.sum(correlations)
print(correlations)
print(weights_correlations)
print("Weights based on correlations: ", weights_correlations)
solver_corr = MOPolicyIteration(P, R, weights_correlations, gamma=gamma, scalarization=scalarization)
solver_corr.train()
if pi_morld.is_in_pareto_archive(solver_corr):
    print("Correlation-based policy is in the Pareto archive.")
policy_corr = solver_corr.policy_table

print(policy_equal)
print(policy_corr)

Equal weights policy is in the Pareto archive.
r_likedness     0.832863
r_usefulness    0.800508
r_return        0.098211
r_adherence     1.000000
r_diversity    -0.005295
Name: completed, dtype: float64
[ 0.30549342  0.29362575  0.03602385  0.3667991  -0.00194213]
Weights based on correlations:  [ 0.30549342  0.29362575  0.03602385  0.3667991  -0.00194213]
Correlation-based policy is in the Pareto archive.
[4 4 5 4 4 5 4 4 4 4 4 3]
[1 1 2 1 1 5 1 4 1 4 2 1]

Format for table in thesis

In [15]:
joint_cluster_to_action = {
        0: ("D", 0),
        1: ("EU", 0),
        2: ("EUD", 0),
        3: ("D", 1),
        4: ("EU", 1),
        5: ("EUD", 1),
    }
def format_action(a):
    cluster, strategy = joint_cluster_to_action[a]
    return f"({cluster},{strategy})"

def format_action_set(actions):
    return r"\{" + ", ".join(format_action(a) for a in actions) + r"\}"

policy_df = pd.DataFrame({
    "State": [f"{idx_to_state[i]}" for i in range(config.NUM_STATES)],
    "B-Corr": [format_action(policy_corr[i]) for i in range(config.NUM_STATES)],
    "B-Eq": [format_action(policy_equal[i]) for i in range(config.NUM_STATES)],
    "MORL-EP": [format_action(best_expert_policy[i]) for i in range(config.NUM_STATES)],
    "MORL-UC": [format_action_set(policy_morl_raw[i]) for i in range(config.NUM_STATES)],
})

latex = policy_df.to_latex(index=False, escape=False)
pyperclip.copy(latex)

policy_df

        State   B-Corr     B-Eq  MORL-EP                       MORL-UC
0   (0, 0, 0)   (EU,0)   (EU,1)   (EU,1)            \{(EU,0), (EU,1)\}
1   (0, 0, 1)   (EU,0)   (EU,1)   (EU,1)   \{(EU,0), (EU,1), (EUD,1)\}
2   (0, 0, 2)  (EUD,0)  (EUD,1)  (EUD,1)  \{(EU,0), (EUD,0), (EUD,1)\}
3   (0, 1, 0)   (EU,0)   (EU,1)  (EUD,1)   \{(EU,0), (EU,1), (EUD,1)\}
4   (0, 1, 1)   (EU,0)   (EU,1)   (EU,1)   \{(EU,0), (EU,1), (EUD,1)\}
5   (0, 1, 2)  (EUD,1)  (EUD,1)   (EU,1)  \{(EUD,0), (EU,1), (EUD,1)\}
6   (1, 0, 0)   (EU,0)   (EU,1)   (EU,1)   \{(EU,0), (EU,1), (EUD,1)\}
7   (1, 0, 1)   (EU,1)   (EU,1)   (EU,1)            \{(EU,0), (EU,1)\}
8   (1, 0, 2)   (EU,0)   (EU,1)   (EU,1)   \{(EU,0), (EU,1), (EUD,1)\}
9   (1, 1, 0)   (EU,1)   (EU,1)   (EU,1)   \{(EU,0), (EU,1), (EUD,1)\}
10  (1, 1, 1)  (EUD,0)   (EU,1)    (D,1)   \{(EU,0), (EU,1), (EUD,1)\}
11  (1, 1, 2)   (EU,0)    (D,1)    (D,1)     \{(EU,0), (D,1), (EU,1)\}

### Single-objective policies

In [16]:
# Policies that only optimize for one objective
single_objective_policies = {}
for i in range(config.NUM_OBJECTIVES):
    weights_single = np.zeros(config.NUM_OBJECTIVES)
    weights_single[i] = 1
    solver_single = MOPolicyIteration(P, R, weights_single, gamma=gamma, scalarization=scalarization)
    solver_single.train()
    if pi_morld.is_in_pareto_archive(solver_single):
        print(f"Single-objective policy for {config.reward_names[i]} is in the Pareto archive.")
    else:
        print(f"Single-objective policy for {config.reward_names[i]} is NOT in the Pareto archive.")
    policy_single = solver_single.policy_table
    single_objective_policies[f"SO-{config.reward_names[i]}"] = policy_single

Single-objective policy for Perceived Enjoyment is in the Pareto archive.
Single-objective policy for Perceived Usefulness is in the Pareto archive.
Single-objective policy for Return Willingness is in the Pareto archive.
Single-objective policy for Adherence is in the Pareto archive.
Single-objective policy for Diversity is NOT in the Pareto archive.

In [17]:
single_policies_df = pd.DataFrame({
    "State": [f"{idx_to_state[i]}" for i in range(config.NUM_STATES)],
    **{f"{config.reward_names[i]}": [format_action(policy_single[i]) for i in range(config.NUM_STATES)] for i, policy_single in enumerate(single_objective_policies.values())}
})
latex_single = single_policies_df.to_latex(index=False, escape=False)
pyperclip.copy(latex_single)

single_policies_df

,State,Perceived Enjoyment,Perceived Usefulness,Return Willingness,Adherence,Diversity
0,"(0, 0, 0)","(EU,0)","(EU,0)","(EU,1)","(EU,0)","(D,1)"
1,"(0, 0, 1)","(EU,1)","(EUD,0)","(EU,0)","(EU,0)","(D,1)"
2,"(0, 0, 2)","(EUD,0)","(EUD,0)","(EU,0)","(EUD,1)","(D,1)"
3,"(0, 1, 0)","(EU,0)","(EU,0)","(EUD,1)","(EU,0)","(EUD,1)"
4,"(0, 1, 1)","(EU,0)","(EU,0)","(EU,0)","(EU,0)","(EU,1)"
5,"(0, 1, 2)","(EUD,1)","(EUD,1)","(EUD,0)","(EUD,1)","(EU,1)"
6,"(1, 0, 0)","(EU,0)","(EU,0)","(EU,0)","(EU,0)","(D,1)"
7,"(1, 0, 1)","(EU,1)","(EU,1)","(D,0)","(EU,1)","(EU,1)"
8,"(1, 0, 2)","(EU,0)","(EU,0)","(D,0)","(EU,1)","(EUD,1)"
9,"(1, 1, 0)","(EU,1)","(EUD,1)","(EUD,1)","(EU,1)","(EU,1)"
10,"(1, 1, 1)","(EUD,0)","(EUD,0)","(D,0)","(EU,0)","(D,1)"
11,"(1, 1, 2)","(EU,0)","(EU,0)","(EU,1)","(EU,0)","(D,1)"

## Run simulations
We first define the number of users and the number of timesteps to simulate

In [ ]:
NUM_USERS = config.NUM_USERS
NUM_TIMESTEPS = config.NUM_TIMESTEPS

save_path = os.path.join(results_folder, model_name, 'simulations')
save = False

#### Simulate comparison policies

In [ ]:
comparison_policies = []

# Random policy
simulation_random = sim_utils.simulate(env, NUM_USERS)
comparison_policies.append(simulation_random)

# Equal weights policy
simulation_equal = sim_utils.simulate(env, NUM_USERS, policy=policy_equal, policy_name="Equal Weights Policy")
comparison_policies.append(simulation_equal)

# Correlation-based policy
simulation_corr = sim_utils.simulate(env, NUM_USERS, policy=policy_corr, policy_name="Correlation-based Policy")
comparison_policies.append(simulation_corr)

# Single-objective policies
for policy_name, policy_single in single_objective_policies.items():
    simulation_single = sim_utils.simulate(env, NUM_USERS, policy=policy_single, policy_name=policy_name)
    comparison_policies.append(simulation_single)

#### Simulate metapolicies

In [ ]:
metapolicies = []

multi_policy_simulation_results_random = sim_utils.simulate_multiple_policies(env, NUM_USERS, selected_policies, top_n_evaluations, selection='most_likely', T=NUM_TIMESTEPS, policy_name="MORL-UC")
metapolicies.append(multi_policy_simulation_results_random)

multi_policy_simulation_results_expert = sim_utils.simulate(env, NUM_USERS, best_expert_policy, "MORL-EP", T=NUM_TIMESTEPS)
metapolicies.append(multi_policy_simulation_results_expert)

multi_policy_simulation_results_combined = sim_utils.simulate_multiple_policies(env, NUM_USERS, selected_policies, top_n_evaluations, selection='combined', T=NUM_TIMESTEPS, policy_name="MORL-UC+EP")
metapolicies.append(multi_policy_simulation_results_combined)

### Analyze and visualize simulations

In [ ]:
combined_df = pd.concat(comparison_policies + metapolicies, ignore_index=True)
pf.interactive_plot_objective(combined_df, config.reward_names)

In [ ]:
# save simulation results
if save:
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    combined_df.to_pickle(os.path.join(save_path, 'combined_simulation_results.pkl'))

#### Inspect adherence

In [ ]:
pf.plot_simulation(combined_df, 'num_completed')

#### Inspect number of users per state

In [ ]:
pf.plot_state_trajectory(combined_df, threshold=1)

#### Inspect diversity

In [ ]:
pf.plot_fraction_completed(combined_df, 4)

#### Analyze dropout / retention

In [ ]:
pf.plot_dropout(combined_df)

### Simulate multiple simulations to get more reliable estimates of dropout and motivation trajectory
In addition to the runs above, we want to get more reliable estimates of expected user retention and motivation trajectories. Therefore, we run multiple simulations for each policy and average the results. This part of the code produced Figure 4.4 in Chapter 4 of the thesis. The results are stored in `simulation_results_multiple_runs.pkl` and can be analyzed in `simulation_analysis.py`. Be aware that this part of the code takes a long time to run.

In [ ]:
num_runs = 20
num_users_per_run = 500

seed = 66 + NUM_USERS  

total_runs = num_runs * num_users_per_run

In [ ]:
comparison_policies_multi_run = []

# Random policy
simulation_random = sim_utils.simulate(env, total_runs, seed=seed)
comparison_policies_multi_run.append(simulation_random)

# Equal weights policy
simulation_equal = sim_utils.simulate(env, total_runs, seed=seed, policy=policy_equal, policy_name="Equal Weights Policy")
comparison_policies_multi_run.append(simulation_equal)

# Correlation-based policy
simulation_corr = sim_utils.simulate(env, total_runs, seed=seed, policy=policy_corr, policy_name="Correlation-based Policy")
comparison_policies_multi_run.append(simulation_corr)

# Single-objective policies
for policy_name, policy_single in single_objective_policies.items():
    simulation_single = sim_utils.simulate(env, total_runs, seed=seed, policy=policy_single, policy_name=policy_name)
    comparison_policies_multi_run.append(simulation_single)

In [ ]:
metapolicies_multi_run = []

multi_policy_simulation_results_random = sim_utils.simulate_multiple_policies(env, total_runs, selected_policies, top_n_evaluations, seed=seed, selection='most_likely', T=NUM_TIMESTEPS, policy_name="MORL-UC")
metapolicies_multi_run.append(multi_policy_simulation_results_random)

multi_policy_simulation_results_expert = sim_utils.simulate(env, total_runs, seed=seed, policy=best_expert_policy, policy_name="MORL-EP", T=NUM_TIMESTEPS)
metapolicies_multi_run.append(multi_policy_simulation_results_expert)

multi_policy_simulation_results_combined = sim_utils.simulate_multiple_policies(env, total_runs, selected_policies, top_n_evaluations, seed=seed, selection='combined', T=NUM_TIMESTEPS, policy_name="MORL-UC+EP")
metapolicies_multi_run.append(multi_policy_simulation_results_combined)

In [ ]:
combined_df_multi_run = pd.concat(comparison_policies_multi_run + metapolicies_multi_run, ignore_index=True)

if save:
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    combined_df_multi_run.to_parquet(os.path.join(save_path, 'combined_simulation_results_multi_run.parquet'))

In [ ]:
palette = sns.color_palette("muted")
sns.set_palette(palette)
sns.set_style("whitegrid")
sns.set_context("paper", font_scale=1.8)


to_show = ["C-Corr", "C-Eq", "MORL-EP", "MORL-UC", "MORL-UC+EP", "Random"]
pf.plot_batched_dropout(combined_df_multi_run[combined_df_multi_run['policy'].isin(to_show)], batch_size=num_users_per_run, n_batches=num_runs, save_path=results_folder + "\\figures\\dropout_over_time.svg")

In [ ]:
pf.plot_batched_dropout(combined_df_multi_run, batch_size=num_users_per_run, n_batches=num_runs, save_path=results_folder + "\\figures\\extra\\dropout_over_time_so.svg")